import React from "react";

const GlobalContext = React.createContext({
  monthIndex: 0,
  setMonthIndex: (index) => {},
  smallCalendarMonth: 0,
  setSmallCalendarMonth: (index) => {},
  daySelected: null,
  setDaySelected: (day) => {},
  startDate: null,
  setStartDate: (startDate) => {},
  eventStartDay: null,
  setEventStartDay: (startDate) => {},
  eventEnd: null,
  setEventEnd: (eventEnd) => {},
  eventStartTime: null,
  setEventStartTime: (eventStartTime) => {},
  eventEndTime: null,
  setEventEndTime: (eventEndTime) => {},
  showEventModal: false,
  setShowEventModal: () => {},
  dataLoaded: false,
  setDataLoaded: () => {},
  dispatchCalEvent: ({ type, payload }) => {},
  dispatchCalEvent2: ({ type, payload }) => {},
  savedEvents: [],
  setsavedEvents: (savedEvents) => {},
  selectedEvent: null,
  setSelectedEvent: () => {},
  setLabels: () => {},
  labels: [],
  updateLabel: () => {},
  filteredEvents: [],
  allEvents: [],
  eventList: [],
  getEvents: () => {},

});

export default GlobalContext;
